language: java
sudo: required
services:
- docker
addons:
  ssh_known_hosts: $DO_SERVER
script:
- docker login
- gradle build docker
- docker push ignatev/lttry
deploy:
  provider: script
  script: ".travis/deploy.sh"
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_ec8b3062fb79_key -iv $encrypted_ec8b3062fb79_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d

